apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{.Values.scale}}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:{{.Values.tag}}
        name: nginx
        ports:
        - containerPort: 80